In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import os

In [19]:
pd.set_option('display.max_columns', None)

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
df=pd.read_csv('churn.csv')

In [22]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure CallService  \
0  2907-ILJBN  Female            0.0     Yes        Yes    11.0         Yes   
1  3896-RCYYE  Female            0.0      No         No    67.0          No   
2  9764-REAFF  Female            0.0     Yes         No    59.0         Yes   
3  6651-RLGGM    Male            0.0     Yes        Yes    67.0         Yes   
4  5879-SESNB  Female            0.0      No         No    11.0         Yes   

  MultipleConnections InternetConnection       OnlineSecurity  \
0                  No                 No  No internet service   
1    No phone service                DSL                   No   
2                  No                 No  No internet service   
3                 Yes                 No  No internet service   
4                 Yes        Fiber optic                   No   

          OnlineBackup DeviceProtectionService        TechnicalHelp  \
0  No internet service     No internet service  No internet service   
1                   No                     Yes                  Yes   
2  No internet service     No internet service  No internet service   
3  No internet service     No internet service  No internet service   
4                   No                      No                   No   

              OnlineTV         OnlineMovies       Agreement BillingMethod  \
0  No internet service  No internet service        One year            No   
1                  Yes                  Yes  Month-to-month           Yes   
2  No internet service  No internet service        Two year            No   
3  No internet service  No internet service        Two year            No   
4                   No                   No  Month-to-month            No   

               PaymentMethod  MonthlyServiceCharges  TotalAmount Churn  
0               Mailed check                  20.60       233.90    No  
1    Credit card (automatic)                  53.40      3579.15    No  
2  Bank transfer (automatic)                  18.40      1057.85    No  
3               Mailed check                  26.30      1688.90    No  
4           Electronic check                  75.25       888.65    No

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12335 entries, 0 to 12334
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   customerID               12335 non-null  object 
 1   gender                   12335 non-null  object 
 2   SeniorCitizen            12335 non-null  float64
 3   Partner                  12335 non-null  object 
 4   Dependents               12335 non-null  object 
 5   tenure                   12335 non-null  float64
 6   CallService              12335 non-null  object 
 7   MultipleConnections      12335 non-null  object 
 8   InternetConnection       12335 non-null  object 
 9   OnlineSecurity           12335 non-null  object 
 10  OnlineBackup             12335 non-null  object 
 11  DeviceProtectionService  12335 non-null  object 
 12  TechnicalHelp            12335 non-null  object 
 13  OnlineTV                 12335 non-null  object 
 14  OnlineMovies          

In [24]:
df.describe()

SeniorCitizen        tenure  MonthlyServiceCharges   TotalAmount
count   12335.000000  12335.000000           12335.000000  12335.000000
mean        0.157254     29.531543              61.502934   2032.263356
std         0.349871     23.342738              28.673113   2120.078007
min         0.000000      1.000000              18.250000     18.800000
25%         0.000000      8.000000              33.886556    352.743728
50%         0.000000     24.000000              64.364917   1209.250000
75%         0.000000     49.000000              85.000000   3168.750000
max         1.000000     72.000000             118.750000   8684.800000

In [25]:
df.drop(['customerID'], axis=1, inplace=True)

In [26]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure CallService  \
0  Female            0.0     Yes        Yes    11.0         Yes   
1  Female            0.0      No         No    67.0          No   
2  Female            0.0     Yes         No    59.0         Yes   
3    Male            0.0     Yes        Yes    67.0         Yes   
4  Female            0.0      No         No    11.0         Yes   

  MultipleConnections InternetConnection       OnlineSecurity  \
0                  No                 No  No internet service   
1    No phone service                DSL                   No   
2                  No                 No  No internet service   
3                 Yes                 No  No internet service   
4                 Yes        Fiber optic                   No   

          OnlineBackup DeviceProtectionService        TechnicalHelp  \
0  No internet service     No internet service  No internet service   
1                   No                     Yes                  Yes   
2  No internet service     No internet service  No internet service   
3  No internet service     No internet service  No internet service   
4                   No                      No                   No   

              OnlineTV         OnlineMovies       Agreement BillingMethod  \
0  No internet service  No internet service        One year            No   
1                  Yes                  Yes  Month-to-month           Yes   
2  No internet service  No internet service        Two year            No   
3  No internet service  No internet service        Two year            No   
4                   No                   No  Month-to-month            No   

               PaymentMethod  MonthlyServiceCharges  TotalAmount Churn  
0               Mailed check                  20.60       233.90    No  
1    Credit card (automatic)                  53.40      3579.15    No  
2  Bank transfer (automatic)                  18.40      1057.85    No  
3               Mailed check                  26.30      1688.90    No  
4           Electronic check                  75.25       888.65    No

In [28]:
df.describe(include='O')

gender Partner Dependents CallService MultipleConnections  \
count    12335   12335      12335       12335               12335   
unique       2       2          2           2                   3   
top     Female     Yes         No         Yes                  No   
freq      6216    6230       7974       10933                5952   

       InternetConnection OnlineSecurity OnlineBackup DeviceProtectionService  \
count               12335          12335        12335                   12335   
unique                  3              3            3                       3   
top           Fiber optic             No           No                      No   
freq                 4995           5773         5118                    5173   

       TechnicalHelp OnlineTV OnlineMovies       Agreement BillingMethod  \
count          12335    12335        12335           12335         12335   
unique             3        3            3               3             2   
top               No       No           No  Month-to-month           Yes   
freq            5863     4592         4620            7058          7053   

           PaymentMethod  Churn  
count              12335  12335  
unique                 4      2  
top     Electronic check     No  
freq                4013   6728

In [29]:
list=['gender','Partner','Dependents','CallService','MultipleConnections','InternetConnection','OnlineSecurity','OnlineBackup','DeviceProtectionService','TechnicalHelp','OnlineTV','OnlineMovies','Agreement','BillingMethod','PaymentMethod','Churn']

In [47]:
cat=[]
for i in df.columns:
    if df.dtypes[i]=='O':
        cat.append(i)
print(cat)
len(cat)

['gender', 'Partner', 'Dependents', 'CallService', 'MultipleConnections', 'InternetConnection', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtectionService', 'TechnicalHelp', 'OnlineTV', 'OnlineMovies', 'Agreement', 'BillingMethod', 'PaymentMethod', 'Churn']


16

In [48]:
for i in cat:
    df=pd.get_dummies(df,columns=[i],drop_first=True ) 


In [66]:
df.head()

SeniorCitizen  tenure  MonthlyServiceCharges  TotalAmount  gender_Male  \
0            0.0    11.0                  20.60       233.90            0   
1            0.0    67.0                  53.40      3579.15            0   
2            0.0    59.0                  18.40      1057.85            0   
3            0.0    67.0                  26.30      1688.90            1   
4            0.0    11.0                  75.25       888.65            0   

   Partner_Yes  Dependents_Yes  CallService_Yes  \
0            1               1                1   
1            0               0                0   
2            1               0                1   
3            1               1                1   
4            0               0                1   

   MultipleConnections_No phone service  MultipleConnections_Yes  \
0                                     0                        0   
1                                     1                        0   
2                                     0                        0   
3                                     0                        1   
4                                     0                        1   

   InternetConnection_Fiber optic  InternetConnection_No  \
0                               0                      1   
1                               0                      0   
2                               0                      1   
3                               0                      1   
4                               1                      0   

   OnlineSecurity_No internet service  OnlineSecurity_Yes  \
0                                   1                   0   
1                                   0                   0   
2                                   1                   0   
3                                   1                   0   
4                                   0                   0   

   OnlineBackup_No internet service  OnlineBackup_Yes  \
0                                 1                 0   
1                                 0                 0   
2                                 1                 0   
3                                 1                 0   
4                                 0                 0   

   DeviceProtectionService_No internet service  DeviceProtectionService_Yes  \
0                                            1                            0   
1                                            0                            1   
2                                            1                            0   
3                                            1                            0   
4                                            0                            0   

   TechnicalHelp_No internet service  TechnicalHelp_Yes  \
0                                  1                  0   
1                                  0                  1   
2                                  1                  0   
3                                  1                  0   
4                                  0                  0   

   OnlineTV_No internet service  OnlineTV_Yes  \
0                             1             0   
1                             0             1   
2                             1             0   
3                             1             0   
4                             0             0   

   OnlineMovies_No internet service  OnlineMovies_Yes  Agreement_One year  \
0                                 1                 0                   1   
1                                 0                 1                   0   
2                                 1                 0                   0   
3                                 1                 0                   0   
4                                 0                 0                   0   

   Agreement_Two year  BillingMethod_Yes  \
0                   0                  0   
1                   0                  1   
2                   1            

In [56]:
# check inbalance 

In [57]:
df['Churn_Yes'].value_counts()

0    6728
1    5607
Name: Churn_Yes, dtype: int64

In [61]:
x=df.iloc[:,0:-1]
y=df.iloc[:, [-1]]

In [62]:
x.head()

SeniorCitizen  tenure  MonthlyServiceCharges  TotalAmount  gender_Male  \
0            0.0    11.0                  20.60       233.90            0   
1            0.0    67.0                  53.40      3579.15            0   
2            0.0    59.0                  18.40      1057.85            0   
3            0.0    67.0                  26.30      1688.90            1   
4            0.0    11.0                  75.25       888.65            0   

   Partner_Yes  Dependents_Yes  CallService_Yes  \
0            1               1                1   
1            0               0                0   
2            1               0                1   
3            1               1                1   
4            0               0                1   

   MultipleConnections_No phone service  MultipleConnections_Yes  \
0                                     0                        0   
1                                     1                        0   
2                                     0                        0   
3                                     0                        1   
4                                     0                        1   

   InternetConnection_Fiber optic  InternetConnection_No  \
0                               0                      1   
1                               0                      0   
2                               0                      1   
3                               0                      1   
4                               1                      0   

   OnlineSecurity_No internet service  OnlineSecurity_Yes  \
0                                   1                   0   
1                                   0                   0   
2                                   1                   0   
3                                   1                   0   
4                                   0                   0   

   OnlineBackup_No internet service  OnlineBackup_Yes  \
0                                 1                 0   
1                                 0                 0   
2                                 1                 0   
3                                 1                 0   
4                                 0                 0   

   DeviceProtectionService_No internet service  DeviceProtectionService_Yes  \
0                                            1                            0   
1                                            0                            1   
2                                            1                            0   
3                                            1                            0   
4                                            0                            0   

   TechnicalHelp_No internet service  TechnicalHelp_Yes  \
0                                  1                  0   
1                                  0                  1   
2                                  1                  0   
3                                  1                  0   
4                                  0                  0   

   OnlineTV_No internet service  OnlineTV_Yes  \
0                             1             0   
1                             0             1   
2                             1             0   
3                             1             0   
4                             0             0   

   OnlineMovies_No internet service  OnlineMovies_Yes  Agreement_One year  \
0                                 1                 0                   1   
1                                 0                 1                   0   
2                                 1                 0                   0   
3                                 1                 0                   0   
4                                 0                 0                   0   

   Agreement_Two year  BillingMethod_Yes  \
0                   0                  0   
1                   0                  1   
2                   1            

In [63]:
y.head()

Churn_Yes
0          0
1          0
2          0
3          0
4          0

In [64]:
# split the data into training and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=101)
# python bydefault consider 75% training and 25% test
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(9868, 30)
(2467, 30)
(9868, 1)
(2467, 1)


In [70]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier(criterion='gini')
model2=DecisionTreeClassifier(criterion='entropy')

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [69]:
y_pred_test_g=model1.predict(x_test)
y_pred_train_g=model1.predict(x_train)

In [71]:
y_pred_test_e=model2.predict(x_test)
y_pred_train_e=model2.predict(x_train)

In [115]:
model1.feature_importances_

array([0.03093841, 0.22503448, 0.26700126, 0.11553331, 0.01440802,
       0.0098807 , 0.01327894, 0.0103311 , 0.00683218, 0.01147264,
       0.01985305, 0.0279485 , 0.02706156, 0.00999348, 0.02210138,
       0.01557842, 0.0103313 , 0.01379219, 0.01771718, 0.01030049,
       0.00543132, 0.01409336, 0.0171229 , 0.01567721, 0.01209215,
       0.01438248, 0.01246655, 0.00819205, 0.0149867 , 0.00616671])

In [90]:
pd.DataFrame(index=X.columns,data=model1.feature_importances_, columns=['feature_importances'])

feature_importances
SeniorCitizen                                           0.030938
tenure                                                  0.225034
MonthlyServiceCharges                                   0.267001
TotalAmount                                             0.115533
gender_Male                                             0.014408
Partner_Yes                                             0.009881
Dependents_Yes                                          0.013279
CallService_Yes                                         0.010331
MultipleConnections_No phone service                    0.006832
MultipleConnections_Yes                                 0.011473
InternetConnection_Fiber optic                          0.019853
InternetConnection_No                                   0.027948
OnlineSecurity_No internet service                      0.027062
OnlineSecurity_Yes                                      0.009993
OnlineBackup_No internet service                        0.022101
OnlineBackup_Yes                                        0.015578
DeviceProtectionService_No internet service             0.010331
DeviceProtectionService_Yes                             0.013792
TechnicalHelp_No internet service                       0.017717
TechnicalHelp_Yes                                       0.010300
OnlineTV_No internet service                            0.005431
OnlineTV_Yes                                            0.014093
OnlineMovies_No internet service                        0.017123
OnlineMovies_Yes                                        0.015677
Agreement_One year                                      0.012092
Agreement_Two year                                      0.014382
BillingMethod_Yes                                       0.012467
PaymentMethod_Credit card (automatic)                   0.008192
PaymentMethod_Electronic check                          0.014987
PaymentMethod_Mailed check                              0.006167

In [89]:
model2.feature_importances_

array([0.03127031, 0.19450146, 0.25531861, 0.11899634, 0.0149281 ,
       0.01092203, 0.01180805, 0.00744459, 0.01169193, 0.01880148,
       0.02076294, 0.0072739 , 0.03654938, 0.01024701, 0.00218704,
       0.01077561, 0.0101783 , 0.01499821, 0.01702481, 0.01166057,
       0.04504258, 0.01045251, 0.02747018, 0.0174698 , 0.01215338,
       0.01864079, 0.01387769, 0.01123065, 0.01881288, 0.00750886])

In [91]:
pd.DataFrame(index=X.columns,data=model2.feature_importances_, columns=['feature_importances'])

feature_importances
SeniorCitizen                                           0.031270
tenure                                                  0.194501
MonthlyServiceCharges                                   0.255319
TotalAmount                                             0.118996
gender_Male                                             0.014928
Partner_Yes                                             0.010922
Dependents_Yes                                          0.011808
CallService_Yes                                         0.007445
MultipleConnections_No phone service                    0.011692
MultipleConnections_Yes                                 0.018801
InternetConnection_Fiber optic                          0.020763
InternetConnection_No                                   0.007274
OnlineSecurity_No internet service                      0.036549
OnlineSecurity_Yes                                      0.010247
OnlineBackup_No internet service                        0.002187
OnlineBackup_Yes                                        0.010776
DeviceProtectionService_No internet service             0.010178
DeviceProtectionService_Yes                             0.014998
TechnicalHelp_No internet service                       0.017025
TechnicalHelp_Yes                                       0.011661
OnlineTV_No internet service                            0.045043
OnlineTV_Yes                                            0.010453
OnlineMovies_No internet service                        0.027470
OnlineMovies_Yes                                        0.017470
Agreement_One year                                      0.012153
Agreement_Two year                                      0.018641
BillingMethod_Yes                                       0.013878
PaymentMethod_Credit card (automatic)                   0.011231
PaymentMethod_Electronic check                          0.018813
PaymentMethod_Mailed check                              0.007509

In [72]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [82]:
print(confusion_matrix(y_train,y_pred_train_g))
print('###'*30)
print(confusion_matrix(y_test,y_pred_test_g))

[[5383    1]
 [   9 4475]]
##########################################################################################
[[1213  131]
 [ 209  914]]


In [83]:
print(confusion_matrix(y_train,y_pred_train_e))
print('###'*30)
print(confusion_matrix(y_test,y_pred_test_e))

[[5383    1]
 [   9 4475]]
##########################################################################################
[[1227  117]
 [ 221  902]]


In [79]:
print(classification_report(y_train,y_pred_train_g))
print('###'*30)
print(classification_report(y_test,y_pred_test_g))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5384
           1       1.00      1.00      1.00      4484

    accuracy                           1.00      9868
   macro avg       1.00      1.00      1.00      9868
weighted avg       1.00      1.00      1.00      9868

##########################################################################################
              precision    recall  f1-score   support

           0       0.85      0.90      0.88      1344
           1       0.87      0.81      0.84      1123

    accuracy                           0.86      2467
   macro avg       0.86      0.86      0.86      2467
weighted avg       0.86      0.86      0.86      2467



In [81]:
print(classification_report(y_train,y_pred_train_e))
print('###'*30)
print(classification_report(y_test,y_pred_test_e))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5384
           1       1.00      1.00      1.00      4484

    accuracy                           1.00      9868
   macro avg       1.00      1.00      1.00      9868
weighted avg       1.00      1.00      1.00      9868

##########################################################################################
              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1344
           1       0.89      0.80      0.84      1123

    accuracy                           0.86      2467
   macro avg       0.87      0.86      0.86      2467
weighted avg       0.86      0.86      0.86      2467



In [118]:
print('Training accuracy for gini',accuracy_score(y_train,y_pred_train_g))
print('###'*30)
print('Testing accuracy for gini',accuracy_score(y_test,y_pred_test_g))

Training accuracy for gini 0.9989866234292664
##########################################################################################
Testing accuracy for gini 0.8621807863802189


In [119]:
print('Training accuracy for entropy',accuracy_score(y_train,y_pred_train_e))
print('###'*30)
print('Testing accuracy for entropy',accuracy_score(y_test,y_pred_test_e))

Training accuracy for entropy 0.9989866234292664
##########################################################################################
Testing accuracy for entropy 0.8629914876368059


In [127]:
from sklearn.model_selection import cross_val_score
accuracy1 = cross_val_score(model1, x_train, y_train, cv=20)
print(accuracy1,'\n')


accuracy2 = cross_val_score(model1, x_test, y_test, cv=20)
print(accuracy2,'\n')

print('best training accuracy for gini',accuracy1[19])
print('best testing accuracy for gini',accuracy2[12])

[0.85425101 0.86639676 0.87044534 0.86639676 0.8805668  0.84008097
 0.86032389 0.82186235 0.85192698 0.8336714  0.82758621 0.87018256
 0.88235294 0.85801217 0.87221095 0.82555781 0.84584178 0.84381339
 0.83975659 0.88843813] 

[0.81451613 0.71774194 0.77419355 0.78225806 0.78225806 0.81451613
 0.79032258 0.7804878  0.83739837 0.79674797 0.80487805 0.82926829
 0.84552846 0.82926829 0.75609756 0.81300813 0.77235772 0.70731707
 0.80487805 0.7804878 ] 

best training accuracy for gini 0.8884381338742393
best testing accuracy for gini 0.8455284552845529


In [129]:
accuracy3 = cross_val_score(model2, x_train, y_train, cv=20)
print(accuracy1,'\n')


accuracy4 = cross_val_score(model2, x_test, y_test, cv=20)
print(accuracy2,'\n')

print('best training accuracy for entropy',accuracy3[19])
print('best testing accuracy for entropy',accuracy4[12])

[0.85425101 0.86639676 0.87044534 0.86639676 0.8805668  0.84008097
 0.86032389 0.82186235 0.85192698 0.8336714  0.82758621 0.87018256
 0.88235294 0.85801217 0.87221095 0.82555781 0.84584178 0.84381339
 0.83975659 0.88843813] 

[0.81451613 0.71774194 0.77419355 0.78225806 0.78225806 0.81451613
 0.79032258 0.7804878  0.83739837 0.79674797 0.80487805 0.82926829
 0.84552846 0.82926829 0.75609756 0.81300813 0.77235772 0.70731707
 0.80487805 0.7804878 ] 

best training accuracy for entropy 0.9026369168356998
best testing accuracy for entropy 0.8699186991869918
